""" Encoding Function Configuration """
encodingFuncConfig = {
                        'uint32' : 'firebolt.Lib.encoders.uint32Encoder',
                        'int32'  : 'firebolt.Lib.encoders.int32Encoder' ,
                        'uint64' : 'firebolt.Lib.encoders.uint64Encoder',
                        'int64'  : 'firebolt.Lib.encoders.int64Encoder' ,
                        'string' : 'firebolt.Lib.encoders.stringEncoder',
                        'ipv4address' : 'firebolt.Lib.encoders.ipv4AddressEncoder',
                        'ipv4addressE164' : 'firebolt.Lib.encoders.ipv4AddressEncoderE164'
                     }

""" Decoding Function Configuration """
decodingFuncConfig = {
                        'uint32' : 'firebolt.Lib.decoders.uint32Decoder',
                        'int32'  : 'firebolt.Lib.decoders.int32Decoder' ,
                        'uint64' : 'firebolt.Lib.decoders.uint64Decoder',
                        'int64'  : 'firebolt.Lib.decoders.int64Decoder' ,
                        'string' : 'firebolt.Lib.decoders.stringDecoder',
                        'ipv4address' : 'firebolt.Lib.decoders.ipv4AddressDecoder',
                        'ipv4addressE164' : 'firebolt.Lib.decoders.ipv4AddressDecoderE164'
                     }

""" Master AVP Repository """
avpPack ={
		'Origin-Host'   	: { 'Code' : 264,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Origin-Realm'  	: { 'Code' : 296,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Auth-Application-Id'	: { 'Code' : 258,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Firmware-Revision'	: { 'Code' : 267,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Host-IP-Address'	: { 'Code' : 257,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Origin-State-ID'	: { 'Code' : 278,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Product-Name'		: { 'Code' : 269,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Vendor-ID'		: { 'Code' : 266,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Result-Code'		: { 'Code' : 268,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Session-ID'		: { 'Code' : 263,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Destination-Realm'	: { 'Code' : 283,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'Service-Context-Id'	: { 'Code' : 461,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'CC-Request-Type'	: { 'Code' : 416,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'CC-Request-Number'	: { 'Code' : 415,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Event-Timestamp'	: { 'Code' : 55, 'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
     'Multiple-Services-Credit-Control' : { 'Code' : 456,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'group'  },
		'Service-Identifier'	: { 'Code' : 439,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Used-Service-Unit'	: { 'Code' : 446,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'group'  },
		'CC-Time'		: { 'Code' : 420,'Mandatory' : 1,'Vendor-ID' : 1,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
		'Reporting-Reason'	: { 'Code' : 872,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 10415, 'Protected' : 0, 'Type' : 'uint32' },
		'Service-Type'		: { 'Code' :1052,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
		'Service-Subtype'	: { 'Code' :1053,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
		'Subscription-ID'	: { 'Code' : 443,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'group'  },
		'Subscription-ID-Type'	: { 'Code' : 450,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Subscription-ID-Data'  : { 'Code' : 444,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'User-Equipment-Info'	: { 'Code' : 458,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'group'  },
	    'User-Equipment-Info-Type'	: { 'Code' : 459,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
	   'User-Equipment-Info-Value'  : { 'Code' : 460,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
		'BFT-ind'		: { 'Code' :25099,'Mandatory' : 0,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
		'Calling-Party-ID'	: { 'Code' :25017,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'group'  },
		'Calling-Party-ID-Type'	: { 'Code' :25019,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
		'Calling-Party-ID-Data' : { 'Code' :25018,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
	     'Calling-Cell-Information' : { 'Code' :25050,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
                'Called-Party-ID'       : { 'Code' :25020,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'group'  },
                'Called-Party-ID-Type'  : { 'Code' :25022,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'uint32' },
                'Called-Party-ID-Data'  : { 'Code' :25021,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
              'Called-Cell-Information' : { 'Code' :25050,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
		'VLR-ID'		: { 'Code' :25005,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
	       'Original-Dialed-Digits' : { 'Code' : 1005,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
		'Destination-Host'	: { 'Code' : 293 ,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'string' },
	    'CC-Service-Specific-Units' : { 'Code' : 417 ,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint64' },
		'Requested-Action'	: { 'Code' : 436 ,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 0, 'Protected' : 0, 'Type' : 'uint32' },
		'Debit-Session-ID' 	: { 'Code' : 25052,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 11580, 'Protected' : 0, 'Type' : 'string' },
	      'Originator-SCCP-Address' : { 'Code' : 2008,'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 10415, 'Protected' : 0, 'Type' : 'string' },
		'Account-Expiration'	: { 'Code' : 2309, 'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 10415, 'Protected' : 0, 'Type' : 'uint32' },
		'Remaining-Balance'	: { 'Code' : 2021, 'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 10415, 'Protected' : 0, 'Type' : 'group' },
		'Cost-Information'	: { 'Code' :  423, 'Mandatory' : 1,'Vendor-ID' : 0,'Vendor-Code' : 10415, 'Protected' : 0, 'Type' : 'group' },



                ##====================================================================================================================================
                # AVP's For Optus Project
                ##====================================================================================================================================
                'Resource-Type'         : { 'Code' : 27163,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint32' },
                'Resource-Type-PP1'     : { 'Code' : 27179,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Resource-Value'        : { 'Code' : 27164,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Resource-Value-PP1'    : { 'Code' : 444,  'Mandatory' : 1, 'Vendor-ID' : 0, 'Vendor-Code' : 0,     'Protected' : 0, 'Type'  : 'string' },
                'Event-Start-Time'      : { 'Code' : 1603, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint32' },
                'Event-Start-Time-PP1'  : { 'Code' : 27165,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Session-ID'            : { 'Code' : 263,  'Mandatory' : 0, 'Vendor-ID' : 0, 'Vendor-Code' : 0,     'Protected' : 0, 'Type'  : 'string' },
                'Usage-ID'              : { 'Code' : 2031, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'uint32' },
                'Usage-ID-PP1'          : { 'Code' : 27161,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Usage-Event-Type'      : { 'Code' : 855,  'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
                'Called-Number'         : { 'Code' : 1004, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Called-Number-PP1'     : { 'Code' : 27166,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Calling-Number'        : { 'Code' : 1003, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Calling-Number-PP1'    : { 'Code' : 27167,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
                'Duration'              : { 'Code' : 1622, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint32' },
                'Duration-PP1'          : { 'Code' : 27168,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'User-Session-Id'	: { 'Code' : 830,  'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'Message-Id'		: { 'Code' : 1210, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'Interface-Id'		: { 'Code' : 2003, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'SMSC-Id'		: { 'Code' : 1010, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'Class'			: { 'Code' : 25,   'Mandatory' : 0, 'Vendor-ID' : 0, 'Vendor-Code' : 0,     'Protected' : 0, 'Type'  : 'string' },
		'Billing-Class'         : { 'Code' : 27162,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint32' },
		'A-Secondary-Time'	: { 'Code' : 27177,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'A-Cell-Id'		: { 'Code' : 1621, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'A-Downlink-Volume' 	: { 'Code' : 1634, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint64' },
		'A-Download-Volume-Text': { 'Code' : 27169,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'A-Uplink-Volume-Text'  : { 'Code' : 27170,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'A-Uplink-Volume'	: { 'Code' : 1635, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint64' },
		'A-provider-id-Text'    : { 'Code' : 27171,'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'A-Provider-Id'		: { 'Code' : 1616, 'Mandatory' : 1, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'Token-Text' 		: { 'Code' : 1215, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'Interface-Text'	: { 'Code' : 2005, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'Sponser-Identify'	: { 'Code' : 531,  'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'string' },
		'Charged-Amount-Text'	: { 'Code' : 27172,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'Charged-Amount'  	: { 'Code' : 1029, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'uint32' },
		'A-Base-amount' 	: { 'Code' : 27173,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
     'A-Original-currency-charge-amount': { 'Code' : 1612, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint64' },
		'A-Foreign-amount'      : { 'Code' : 27174,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
	'A-Original-currency-tax-amount': { 'Code' : 1614, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 10415, 'Protected' : 0, 'Type'  : 'uint64' },
		'A-Original-currency'   : { 'Code' : 1611, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'OFCA-Recycle-Indicator': { 'Code' : 27175,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'Physical-File-ID'      : { 'Code' : 27176,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' },
		'Physical-File-Sequence': { 'Code' : 27178,'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'uint64' },
		'CC-Request-Number'	: { 'Code' : 415,  'Mandatory' : 0, 'Vendor-ID' : 0, 'Vendor-Code' : 0,     'Protected' : 0, 'Type'  : 'uint32' },
		'CC-Request-Type'	: { 'Code' : 416,  'Mandatory' : 0, 'Vendor-ID' : 0, 'Vendor-Code' : 0,     'Protected' : 0, 'Type'  : 'uint32' },
		'TimeZone'              : { 'Code' : 1501, 'Mandatory' : 0, 'Vendor-ID' : 1, 'Vendor-Code' : 11580, 'Protected' : 0, 'Type'  : 'string' }
	  }		
